### ISSUE TITLE
Weddding venues: lista de venues en tamaño minimo

### ISSUE THREAD

**Issue by alesanchezr** [caenavgu/bmw-template#14]
El menu cambia correctamente de layout cuando entramos a tamaño mobile, las fotos de los venues se colocan del lado izquierdo. Pero si seguimos disminuyendo el tamaño en XS el menu regresa a tener las fotos de los venues arriba (como si fuera tamaño desktop), deberían mantenerse a la izquierda.
![c7gihlu9u1](https://user-images.githubusercontent.com/426452/38202355-66846558-3669-11e8-8901-922b3eb06614.gif)

**Comment by caenavgu** [comment]
DONE
